=== thejos/SOAPWebService/SOAPwsTranslator/src/java/service/documents/srb_eng_esp_dictionary.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="dictionary">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="word" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="word">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="serbian" type="xs:string" />
				<xs:element name="english" type="xs:string" />
				<xs:element name="spanish" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== thejos/SOAPWebService/SOAPwsTranslator/src/java/service/documents/srb_eng_esp_dictionary.xml
<?xml version='1.0' encoding='UTF-8'?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="srb_eng_esp_dictionary.xsd">
    <word>
        <serbian>biljka</serbian>
        <english>plant</english>
        <spanish>planta</spanish>
    </word>
    <word>
        <serbian>drvo</serbian>
        <english>tree</english>
        <spanish>madera</spanish>
    </word>
    <word>
        <serbian>list</serbian>
        <english>leaf</english>
        <spanish>hoja</spanish>
    </word>
    <word>
        <serbian>leptir</serbian>
        <english>butterfly</english>
        <spanish>mariposa</spanish>
    </word>
    <word>
        <serbian>voda</serbian>
        <english>water</english>
        <spanish>agua</spanish>
    </word>
</dictionary>
